### ISSUE TITLE
I am having ImportError

### ISSUE THREAD

**Issue by NIRAVDEV** [autodistill/autodistill-grounding-dino#13]
Traceback (most recent call last):
  File "c:\Users\HP\Documents\GitHub\autodistill-grounding-dino\autodistill.py", line 11, in <module>
    from autodistill_grounding_dino import GroundingDINO
  File "c:\Users\HP\Documents\GitHub\autodistill-grounding-dino\autodistill_grounding_dino\__init__.py", line 1, in <module>
    from autodistill_grounding_dino import GroundingDINO
ImportError: cannot import name 'GroundingDINO' from partially initialized module 'autodistill_grounding_dino' (most likely due to a circular import) (c:\Users\HP\Documents\GitHub\autodistill-grounding-dino\autodistill_grounding_dino\__init__.py)

**Comment by capjamesg** [comment]
Hello there! Can you run `pip install --upgrade autodistill-grounding-dino` and let us know if you are still running into issues?

**Comment by NIRAVDEV** [comment]
Same Issues

**Comment by qiaoran437** [comment]
Collecting rf-groundingdino==0.1.2 (from autodistill-grounding-dino)
  Using cached rf_groundingdino-0.1.2.tar.gz (82 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\27787\AppData\Local\Temp\pip-install-zb6csqu5\rf-groundingdino_02d96e7a336643598078cd622d733011\setup.py", line 41, in <module>
          readme = readme_file.read()
                   ^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 2875: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
