### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by gkadntmd** [autodistill/autodistill-grounding-dino#9]
I downloaded using pip, but an encoding error occurred and installation failed. I tried setting up pythonencoding and tried setup install using the github code, but it didn't install. help!!

os:windows11

error code:
 Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\hamus\AppData\Local\Temp\pip-install-rrfskxhd\rf-groundingdino_0a91a8aabc5a4cae8bb26b38a88dde28\setup.py", line 41, in <module>
          readme = readme_file.read()
      UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 2873: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by illdoCc** [comment]
I have the same question.
